[package]
name = "axum-can"
version = "0.1.0"
edition = "2024"



[dependencies]
async-trait = "0.1.8"
axum = { version = "0.8.9", features = ["ws"] }
can-dbc = "6.0.0"
futures = "0.3.30"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = { version = "1.0.104", features = ["preserve_order"] }
socketcan = { version = "3.5.0", features = ["tokio"] }
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.38"
tokio = { version = "1.35.1", features = ["full", "test-util"] }
tokio-util = "0.7.18"
tower-http = { version = "0.6.0", features = ["fs"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3.23.0"
tokio-tungstenite = "0.29.0"
