[package]
name = "axum-can-socketcan-example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
socketcan = { version = "=3.5.0", features = ["tokio"] }
tokio = { version = "1.35", features = ["fs", "macros", "rt-multi-thread", "time"] }
toml = "0.8"
